### ISSUE TITLE
Quiz-Review not loading

### ISSUE THREAD

**Issue by pascalschaerli1989** [wiris/moodle-qtype_wq#63]
Hi

The follow error appears if a student finishs his quiz. We use Moodle 3.10 with PHP 7.4.28.
out of nothing. it didn't work anymore. please help me.

[BUG Wiris.txt](https://github.com/wiris/moodle-qtype_wq/files/8224061/BUG.Wiris.txt)

uncaught exception: Call to a member function release() on bool

in file: /home/stromna1/public_html/lernplattform/question/type/wq/classes/moodlelockprovider.class.php line 56
#0 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/SharedVariables.class.php(22): moodlelockprovider->getLock('wiris_maxconnec...')
#1 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/MaxConnectionsHttpImpl.class.php(19): com_wiris_quizzes_impl_SharedVariables->lockVariable('wiris_maxconnec...')
#2 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/MaxConnectionsHttpImpl.class.php(84): com_wiris_quizzes_impl_MaxConnectionsHttpImpl->getConnectionSlot()
#3 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/QuizzesServiceImpl.class.php(43): com_wiris_quizzes_impl_MaxConnectionsHttpImpl->request(true)
#4 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/QuizzesServiceImpl.class.php(54): com_wiris_quizzes_impl_QuizzesServiceImpl->callService(Object(com_wiris_quizzes_impl_MultipleQuestionRequest), false, Object(com_wiris_quizzes_impl_QuizzesServiceSyncListener), false)
#5 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/QuizzesServiceImpl.class.php(58): com_wiris_quizzes_impl_QuizzesServiceImpl->executeMultipleImpl(Object(com_wiris_quizzes_impl_MultipleQuestionRequest), Object(com_wiris_quizzes_impl_QuizzesServiceSyncListener), false)
#6 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/impl/QuizzesServiceImpl.class.php(84): com_wiris_quizzes_impl_QuizzesServiceImpl->executeMultiple(Object(com_wiris_quizzes_impl_MultipleQuestionRequest))
#7 /home/stromna1/public_html/lernplattform/question/type/wq/quizzes/lib/com/wiris/quizzes/wrap/QuizzesServiceWrap.class.php(30): com_wiris_quizzes_impl_QuizzesServiceImpl->execute(Object(com_wiris_quizzes_impl_QuestionRequestImpl))
#8 /home/stromna1/public_html/lernplattform/question/type/wq/question.php(351): com_wiris_quizzes_wrap_QuizzesServiceWrap->execute(Object(com_wiris_quizzes_impl_QuestionRequestImpl))
#9 /home/stromna1/public_html/lernplattform/question/type/shortanswerwiris/question.php(188): qtype_wq_question->call_wiris_service(Object(com_wiris_quizzes_wrap_QuestionRequestWrap))
#10 /home/stromna1/public_html/lernplattform/question/type/shortanswerwiris/question.php(81): qtype_shortanswerwiris_question->get_matching_answer(Array)
#11 /home/stromna1/public_html/lernplattform/question/behaviour/immediatefeedback/behaviour.php(131): qtype_shortanswerwiris_question->grade_response(Array)
#12 /home/stromna1/public_html/lernplattform/question/behaviour/immediatefeedback/behaviour.php(85): qbehaviour_immediatefeedback->process_finish(Object(question_attempt_pending_step))
#13 /home/stromna1/public_html/lernplattform/question/engine/questionattempt.php(1356): qbehaviour_immediatefeedback->process_action(Object(question_attempt_pending_step))
#14 /home/stromna1/public_html/lernplattform/question/engine/questionattempt.php(1396): question_attempt->process_action(Array, 1646921576, NULL)
#15 /home/stromna1/public_html/lernplattform/question/engine/questionusage.php(859): question_attempt->finish(1646921576)
#16 /home/stromna1/public_html/lernplattform/mod/quiz/attemptlib.php(2171): question_usage_by_activity->finish_all_questions(1646921576)
#17 /home/stromna1/public_html/lernplattform/mod/quiz/attemptlib.php(2443): quiz_attempt->process_finish(1646921576, true)
#18 /home/stromna1/public_html/lernplattform/mod/quiz/processattempt.php(89): quiz_attempt->process_attempt(1646921576, 1, 0, 0)
#19 {main}

**Comment by nightshadetvn** [comment]
Same goes for me! We use moodle 4.1.1+ and php 7.4.33 and nothing works for us…

**Comment by nightshadetvn** [comment]
NOTE : the thing that worked out to me was deleting the thing that caused problems and it hasn't affected anything
